project:
  type: website
  output-dir: docs

website:
  title: Relacyjne Systemy Organizacji Danych
  description: "Relacyjne Systemy Organizacji Danych dla studentów WAT w Warszawie"
  site-url: https://sebkaz-teaching.github.io/rsod2026
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - section: "Wykłady"
        contents:
          - lectures/wyklad1.qmd
          - lectures/wyklad2.qmd
          - lectures/wyklad3.qmd
          - lectures/wyklad4.qmd
          - lectures/wyklad5.qmd
  page-footer: "Copyright 2026, Sebastian Zając"
format:
  html:
    page-layout: article
    css: style.css
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    self-contained-math: true
    code-overflow: wrap
    highlight-style: dark
    code-block-background: true
    link-external-newwindow: true
